### ISSUE TITLE
Speed parameter 

### ISSUE THREAD

**Issue by jtorde** [qwerty35/swarm_simulator#2]
Hi

First of all, thanks a lot for releasing this code! I've been running some simulations, and I've one question: What's the value "speed" in [this line](https://github.com/qwerty35/swarm_simulator/blob/master/swarm_planner/missions/mission_16agents_15.json#L8)? I've seen that that value is stored in [this vector ](https://github.com/qwerty35/swarm_simulator/blob/master/swarm_planner/include/mission.hpp#L68). But is that vector used elsewhere in the code?

Thanks!

**Comment by qwerty35** [comment]
The speed parameter indicates a nominal speed of quadrotor, but it is not utilized in this work due to limitation of the ECBS algorithm. (ECBS needs the assumption that the speeds of all quadrotors are equal.) It will be used in future work. Thank you for your attention!
