### ISSUE TITLE
Error while catkin_make

### ISSUE THREAD

**Issue by Iko-Git** [qwerty35/swarm_simulator#6]
Thanks for providing the software of the paper.
I'd like to kindly ask about an error I am facing while performing `catkin_make`, I am using ROS melodic, and with respect to the dependencies:
- I am assuming that cplex got installed correctly, and got added to the cMakeLists.txt of your pkg
- Did perform 
sudo apt-get install ros-melodic-octomap
sudo apt-get install ros-melodic-octovis
sudo apt-get install python-matplotlib python-numpy python2.7-dev
- cloned the pkg provided by the link https://github.com/whoenig/libMultiRobotPlanning, and applied `cmake ..` and `make`

the error is shown below:
```

CMake Error at swarm_simulator/swarm_planner/CMakeLists.txt:34 (find_package):
  By not providing "FinddynamicEDT3D.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "dynamicEDT3D", but CMake did not find one.

  Could not find a package configuration file provided by "dynamicEDT3D" with
  any of the following names:

    dynamicEDT3DConfig.cmake
    dynamicedt3d-config.cmake

  Add the installation prefix of "dynamicEDT3D" to CMAKE_PREFIX_PATH or set
  "dynamicEDT3D_DIR" to a directory containing one of the above files.  If
  "dynamicEDT3D" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/jack/catkin_ws2/build/CMakeFiles/CMakeOutput.log".
See also "/home/jack/catkin_ws2/build/CMakeFiles/CMakeError.log".
Makefile:320: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

```

**Comment by qwerty35** [comment]
We found that some important commands are missed, so we fixed README file.
For your problem, try this in your terminal.
sudo apt-get install ros-melodic-dynamic-edt-3d
If this command cannot solve the problem, please let me know. Thank you!

**Comment by Iko-Git** [comment]
Thanks for your modification. Thereby, the `catkin_make `worked correctly.

**Comment by Iko-Git** [comment]
After running `sudo apt-get install ros-melodic-octomap ros-melodic-octomap-mapping ros-melodic-octomap-msgs ros-melodic-octomap-ros ros-melodic-octomap-rviz-plugins ros-melodic-octomap-server
` I started not to face the error mentioned in the previous comment. However, the following error started to be faced while running the demo via` roslaunch swarm_planner plan_rbp_random_forest.launch`
```
ERROR: cannot launch node of type [swarm_planner/random_map_generator]: Cannot locate node of type [random_map_generator] in package [swarm_planner]. Make sure file exists in package path and permission is set to executable (chmod +x)
ERROR: cannot launch node of type [swarm_planner/swarm_traj_planner_rbp]: Cannot locate node of type [swarm_traj_planner_rbp] in package [swarm_planner]. Make sure file exists in package path and permission is set to executable (chmod +x)

```
