### ISSUE TITLE
How to create a new map?

### ISSUE THREAD

**Issue by JACKLiuDay** [qwerty35/swarm_simulator#9]
Hi, thank you for your great work about swarm simulator. I want to create a map for my lab. But I don't know how to do it with swarm simulator. Could you give me some advice. Thanks.

**Comment by qwerty35** [comment]
This simulator receives the Octomap bt file as a map input.
There are various ways to generate Octomap, and I recommend using an external package such as octomap_server (http://wiki.ros.org/octomap_server)
First, publish the desired map as a ROS pointcloud2 message.
If you can't publish the map as a pointcloud2 message, you may need to write a bridge node for message conversion.
Second, use the octomap_saver node to save the pointcloud2 as an Octomap bt file (See 2.4 in the above link)

**Comment by JACKLiuDay** [comment]
> This simulator receives the Octomap bt file as a map input. There are various ways to generate Octomap, and I recommend using an external package such as octomap_server (http://wiki.ros.org/octomap_server) First, publish the desired map as a ROS pointcloud2 message. If you can't publish the map as a pointcloud2 message, you may need to write a bridge node for message conversion. Second, use the octomap_saver node to save the pointcloud2 as an Octomap bt file (See 2.4 in the above link)

Thank you so much for your reply. I will try it.
